[project]
database_url = "postgresql://postgres:postgres@localhost:54322/postgres"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
autoconfirm = true
disable_signup = false
jwt_expiry = 3600
enable_signup = true

[auth.email]
enabled = true

[postgres]
port = 5432
max_connections = 100

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "extensions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
shadow_database_url = ""
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"
